# Generated by Django 5.2.8 on 2025-11-27 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_student_enrolled_courses_courserating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseRating',
        ),
    ]
